###
GET http://localhost:4005/odata/v4/school/Students?$expand=to_StudentMarks


###
POST  http://localhost:4004/odata/v4/school/Students
Content-Type: application/json

{
    "student_id":"3001",
    "student_name":"Parthipan"
}


###
PATCH http://localhost:4004/odata/v4/school/Students(student_id='3001')
Content-Type: application/json

{
    "student_name":"Suganya"
}


###
DELETE http://localhost:4005/odata/v4/school/Students(student_id='2001')


###
GET http://localhost:4004/odata/v4/school/Students(student_id='1001')


###
GET http://localhost:4004/odata/v4/school/Students(student_id='1001')


###
GET http://localhost:4004/odata/v4/school/StudentMarks?$filter=student_id eq '1001'



###
GET http://localhost:4004/odata/v4/school/StudentFees?$filter=student_id eq '1001'



###
GET http://localhost:4004/odata/v4/school/CompleteStudentInfo(student_id='1001')


###
POST  http://localhost:4004/odata/v4/school/Student_Hostel
Content-Type: application/json

{

    "room_no":"223"
}


###
GET http://localhost:4004/odata/v4/college/GetAllPersonData(Input='1001')